---
version: "3.8"
services:
  frontend:
    build:
      context: .
      target: nodebase
    command: ["sh", "-c", "yarn install && yarn run serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web:/src"
      - "node_cache:/src/node_modules"
  backend:
    build:
      context: .
      target: gobase
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
      - "go_cache:/go/pkg"
volumes:
  node_cache:
  go_cache:
