---
version: "3.8"
services:
  frontend:
    build:
      context: .
      target: nodebase
    init: true
    command: ["yarn", "run", "serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web:/src/web"
      - "node_cache:/src/web/node_modules"
  backend:
    build:
      context: .
      target: gobase
    init: true
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
      - "go_cache:/go/pkg"
volumes:
  node_cache:
  go_cache:
