---
name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - name: Setup Node
        uses: actions/setup-node@v1.1.0
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install tools
        run: |
          go get -u github.com/kevinburke/go-bindata/...
          go get -u golang.org/x/lint/golint
      - name: Node Dependencies
        working-directory: web
        run: yarn install --no-progress
      - name: Go Dependencies
        run: go mod download
      - name: Node Lint
        working-directory: web
        run: yarn run lint --no-progress
      - name: Go Lint
        run: |
          export PATH=/home/runner/go/bin:$PATH
          go vet ./...
          golint ./...
      - name: Node Build
        working-directory: web
        run: yarn run build --no-progress --production

      - name: Go Build
        run: |
          export PATH=/home/runner/go/bin:$PATH
          go generate -v api/api.go
          go build -v -o bookmarks --tags "fts5"

  docker:
    name: Docker
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Docker Build
        run: |
          docker build \
            --build-arg "VERSION=$(git describe --tags)" \
            --build-arg "COMMIT=$(git describe --always)" \
            --build-arg "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --tag "${{ github.repository }}:latest" .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin

      - name: Docker Push
        run: |
          docker push "${{ github.repository }}:latest"
